name: Cache node_modules and dist
description: Caches the node_modules and optionally dist.
inputs:
    node-modules:
        description: Whether to cache node_modules.
        default: 'true'
    shared-dist:
        description: Whether to cache shared/dist.
        default: 'true'
outputs:
    node-modules-cache-hit:
        description: 'true if node_modules could be restored from cache'
        value: ${{ steps.cache-node-modules.outputs.cache-hit }}
    shared-dist-cache-hit:
        description: 'true if shared/dist could be restored from cache'
        value: ${{ steps.cache-shared-dist.outputs.cache-hit }}

runs:
    using: composite
    steps:
        - name: Cache node modules
          if: ${{ inputs.node-modules == 'true' }}
          uses: actions/cache@v3
          id: cache-node-modules
          with:
              path: |
                  node_modules
                  shared/node_modules
                  frontend/node_modules
                  backend/node_modules
              key: node-modules-${{ hashFiles('package-lock.json', '**/package-lock.json') }}-${{ runner.os }}
        - name: Cache shared/dist
          if: ${{ inputs.shared-dist == 'true' }}
          uses: actions/cache@v3
          id: cache-shared-dist
          with:
              path: shared/dist
              key: shared-dist-${{ hashFiles('shared/src/**') }}-${{ runner.os }}
