#!/bin/sh

# creating new session ticket, for Forward Secrecy
openssl rand 80 > /run/session_ticket.key
chown www-data:www-data /run/session_ticket.key
chmod 400 /run/session_ticket.key

nginx -s reload

# needed after each start/restart/reload of nginx
# search on the web for "nginx OCSP prefetching" - nginx doesn't automatically prefetch the OCSP response after start/restart/reload
# otherwise the first access (at least on Firefox) will result in "Secure Connection Failed"
set +e
curl https://${DFM_DOMAIN} > /dev/null 2>&1
set -e
