name: Add commit hash to version
description: Adds the current branch name and commit hash as suffix to the current version number
runs:
    using: composite
    steps:
        - name: Get version
          id: get-version
          run: |
              versionName=`jq -jM .version package.json`
              echo "VERSION=$versionName" >> $GITHUB_OUTPUT
          shell: bash
        - name: Get suffix
          id: get-suffix
          run: echo "SUFFIX=$(git branch --show-current).$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          shell: bash
        - name: Add suffix to version number
          uses: ./.github/actions/update-version
          with:
              version: '${{ steps.get-version.outputs.VERSION }}+${{ steps.get-suffix.outputs.SUFFIX }}'
